"""Tests for the bundler component-renaming conflict check (P-040)."""

from __future__ import annotations

import os
import subprocess
from pathlib import Path
from unittest.mock import Mock

from validation.context import ApiContext, ValidationContext


_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
_REDOCLY_BIN_DIR = _REPO_ROOT / "validation" / "node_modules" / ".bin"


def _make_context(api_name: str | None = None) -> ValidationContext:
    apis = ()
    if api_name is not None:
        apis = (
            ApiContext(
                api_name=api_name,
                target_api_version="0.1.0",
                target_api_status="alpha",
                target_api_maturity="initial",
                api_pattern="request-response",
                spec_file=f"code/API_definitions/{api_name}.yaml",
            ),
        )
    return ValidationContext(
        repository="TestRepo",
        branch_type="main",
        trigger_type="dispatch",
        profile="advisory",
        stage="enabled",
        target_release_type=None,
        commonalities_release=None,
        commonalities_version=None,
        icm_release=None,
        base_ref=None,
        is_release_review_pr=False,
        release_plan_changed=None,
        pr_number=None,
        apis=apis,
        workflow_run_url="",
        tooling_ref="",
    )


def _write_spec(tmp_path: Path, name: str, content: str) -> Path:
    api_dir = tmp_path / "code" / "API_definitions"
    api_dir.mkdir(parents=True, exist_ok=True)
    path = api_dir / f"{name}.yaml"
    path.write_text(content, encoding="utf-8")
    return path


_NO_EXTERNAL_REF = """\
openapi: 3.0.3
info:
  title: Sample
  version: 0.1.0
paths:
  /ping:
    get:
      operationId: ping
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foo'
components:
  schemas:
    Foo:
      type: string
"""

_WITH_EXTERNAL_REF = """\
openapi: 3.0.3
info:
  title: Sample
  version: 0.1.0
paths:
  /ping:
    get:
      operationId: ping
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foo'
        '500':
          description: err
          content:
            application/json:
              schema:
                $ref: '../common/common.yaml#/components/schemas/Foo'
components:
  schemas:
    Foo:
      type: string
"""

_CONFLICT_STDERR_SINGLE = """\
bundling code/API_definitions/sample.yaml...
[1] code/API_definitions/sample.yaml:21:17 at #/paths/~1ping/get/responses/500/content/application~1json/schema

Two schemas are referenced with the same name but different content. Renamed Foo to Foo-2.

Error was generated by the bundler rule.

❌ Errors encountered while bundling code/API_definitions/sample.yaml: bundle not created (use --force to ignore errors).
"""

_CONFLICT_STDERR_DOUBLE = """\
bundling code/API_definitions/sample.yaml...
[1] code/API_definitions/sample.yaml:21:17 at #/paths/~1ping/get/responses/500/content/application~1json/schema

Two schemas are referenced with the same name but different content. Renamed Foo to Foo-2.

[2] code/API_definitions/sample.yaml:29:17 at #/paths/~1pong/get/responses/500/content/application~1json/schema

Two schemas are referenced with the same name but different content. Renamed Bar to Bar-2.

❌ Errors encountered while bundling code/API_definitions/sample.yaml: bundle not created (use --force to ignore errors).
"""

_UNRELATED_FAILURE_STDERR = """\
bundling code/API_definitions/sample.yaml...
[1] code/API_definitions/sample.yaml:12:17 at #/paths/~1ping/get/responses/200/content/application~1json/schema

Can't resolve $ref

❌ Errors encountered while bundling code/API_definitions/sample.yaml: bundle not created (use --force to ignore errors).
"""


class TestCheckComponentRenamingConflict:
    def test_no_api_context_returns_no_findings(self, tmp_path: Path, monkeypatch):
        from validation.engines.python_checks import bundling_checks

        run = Mock()
        monkeypatch.setattr(bundling_checks.subprocess, "run", run)

        findings = bundling_checks.check_component_renaming_conflict(
            tmp_path, _make_context()
        )

        assert findings == []
        run.assert_not_called()

    def test_missing_spec_file_returns_no_findings(self, tmp_path: Path, monkeypatch):
        from validation.engines.python_checks import bundling_checks

        run = Mock()
        monkeypatch.setattr(bundling_checks.subprocess, "run", run)

        findings = bundling_checks.check_component_renaming_conflict(
            tmp_path, _make_context("sample")
        )

        assert findings == []
        run.assert_not_called()

    def test_no_external_ref_skips_subprocess(self, tmp_path: Path, monkeypatch):
        from validation.engines.python_checks import bundling_checks

        _write_spec(tmp_path, "sample", _NO_EXTERNAL_REF)
        run = Mock()
        monkeypatch.setattr(bundling_checks.subprocess, "run", run)

        findings = bundling_checks.check_component_renaming_conflict(
            tmp_path, _make_context("sample")
        )

        assert findings == []
        run.assert_not_called()

    def test_clean_bundle_returns_no_findings(self, tmp_path: Path, monkeypatch):
        from validation.engines.python_checks import bundling_checks

        _write_spec(tmp_path, "sample", _WITH_EXTERNAL_REF)
        monkeypatch.setattr(
            bundling_checks.subprocess,
            "run",
            Mock(return_value=subprocess.CompletedProcess([], 0, stdout="", stderr="")),
        )

        findings = bundling_checks.check_component_renaming_conflict(
            tmp_path, _make_context("sample")
        )

        assert findings == []

    def test_single_conflict_produces_one_finding(self, tmp_path: Path, monkeypatch):
        from validation.engines.python_checks import bundling_checks

        _write_spec(tmp_path, "sample", _WITH_EXTERNAL_REF)
        monkeypatch.setattr(
            bundling_checks.subprocess,
            "run",
            Mock(
                return_value=subprocess.CompletedProcess(
                    [], 1, stdout="", stderr=_CONFLICT_STDERR_SINGLE
                )
            ),
        )

        findings = bundling_checks.check_component_renaming_conflict(
            tmp_path, _make_context("sample")
        )

        assert len(findings) == 1
        finding = findings[0]
        assert finding["engine"] == "python"
        assert finding["engine_rule"] == "check-component-renaming-conflict"
        assert finding["level"] == "error"
        assert finding["path"] == "code/API_definitions/sample.yaml"
        assert finding["line"] == 1
        assert finding["api_name"] == "sample"
        assert "Foo" in finding["message"]
        assert "Foo-2" in finding["message"]
        assert "isn't yours to rename" in finding["message"]

    def test_multiple_conflicts_produce_multiple_findings(
        self, tmp_path: Path, monkeypatch
    ):
        from validation.engines.python_checks import bundling_checks

        _write_spec(tmp_path, "sample", _WITH_EXTERNAL_REF)
        monkeypatch.setattr(
            bundling_checks.subprocess,
            "run",
            Mock(
                return_value=subprocess.CompletedProcess(
                    [], 1, stdout="", stderr=_CONFLICT_STDERR_DOUBLE
                )
            ),
        )

        findings = bundling_checks.check_component_renaming_conflict(
            tmp_path, _make_context("sample")
        )

        assert len(findings) == 2
        messages = " ".join(f["message"] for f in findings)
        assert "Foo" in messages
        assert "Bar" in messages

    def test_unrelated_bundle_failure_returns_no_findings(
        self, tmp_path: Path, monkeypatch
    ):
        from validation.engines.python_checks import bundling_checks

        _write_spec(tmp_path, "sample", _WITH_EXTERNAL_REF)
        monkeypatch.setattr(
            bundling_checks.subprocess,
            "run",
            Mock(
                return_value=subprocess.CompletedProcess(
                    [], 1, stdout="", stderr=_UNRELATED_FAILURE_STDERR
                )
            ),
        )

        findings = bundling_checks.check_component_renaming_conflict(
            tmp_path, _make_context("sample")
        )

        assert findings == []

    def test_subprocess_missing_returns_execution_error(
        self, tmp_path: Path, monkeypatch
    ):
        from validation.engines.python_checks import bundling_checks

        _write_spec(tmp_path, "sample", _WITH_EXTERNAL_REF)
        monkeypatch.setattr(
            bundling_checks.subprocess,
            "run",
            Mock(side_effect=FileNotFoundError("redocly not found")),
        )

        findings = bundling_checks.check_component_renaming_conflict(
            tmp_path, _make_context("sample")
        )

        assert len(findings) == 1
        assert findings[0]["engine_rule"] == "component-renaming-conflict-execution-error"
        assert findings[0]["level"] == "error"

    def test_subprocess_timeout_returns_execution_error(
        self, tmp_path: Path, monkeypatch
    ):
        from validation.engines.python_checks import bundling_checks

        _write_spec(tmp_path, "sample", _WITH_EXTERNAL_REF)
        monkeypatch.setattr(
            bundling_checks.subprocess,
            "run",
            Mock(side_effect=subprocess.TimeoutExpired(cmd="redocly", timeout=60)),
        )

        findings = bundling_checks.check_component_renaming_conflict(
            tmp_path, _make_context("sample")
        )

        assert len(findings) == 1
        assert findings[0]["engine_rule"] == "component-renaming-conflict-execution-error"
        assert findings[0]["level"] == "error"


class TestComponentRenamingConflictIntegration:
    """Exercises the real ``redocly`` binary, not a mocked subprocess.

    Guards against Redocly changing its renaming-conflict message shape out
    from under ``_CONFLICT_RE``.
    """

    def _run_with_real_redocly(self, tmp_path, monkeypatch, api_name):
        from validation.engines.python_checks import bundling_checks

        monkeypatch.setenv("PATH", f"{_REDOCLY_BIN_DIR}{os.pathsep}{os.environ['PATH']}")
        return bundling_checks.check_component_renaming_conflict(
            tmp_path, _make_context(api_name)
        )

    def test_real_conflict_is_detected(self, tmp_path: Path, monkeypatch):
        common_dir = tmp_path / "code" / "common"
        common_dir.mkdir(parents=True)
        (common_dir / "common.yaml").write_text(
            "components:\n"
            "  schemas:\n"
            "    Foo:\n"
            "      type: object\n"
            "      properties:\n"
            "        bar:\n"
            "          type: string\n",
            encoding="utf-8",
        )
        _write_spec(tmp_path, "sample", _WITH_EXTERNAL_REF)

        findings = self._run_with_real_redocly(tmp_path, monkeypatch, "sample")

        assert len(findings) == 1
        assert findings[0]["engine_rule"] == "check-component-renaming-conflict"
        assert "Foo" in findings[0]["message"]

    def test_real_proxy_with_matching_content_is_not_flagged(
        self, tmp_path: Path, monkeypatch
    ):
        common_dir = tmp_path / "code" / "common"
        common_dir.mkdir(parents=True)
        (common_dir / "common.yaml").write_text(
            "components:\n" "  schemas:\n" "    Foo:\n" "      type: string\n",
            encoding="utf-8",
        )
        _write_spec(tmp_path, "sample", _WITH_EXTERNAL_REF)

        findings = self._run_with_real_redocly(tmp_path, monkeypatch, "sample")

        assert findings == []
