name: Caller for Spectral linting with CAMARA ruleset
# CAMARA Project - Github Action for Pull Reqests
# This workflow calls the reusable workflow from the tooling repository
# initial version

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  pull-requests: write
  contents: write
  issues: write

jobs:
  spectral:
    uses: camaraproject/tooling/.github/workflows/spectral-oas.yml@main
# This workflow calls the reusable workflow from the tooling repository
# Tools configuration from the tooling repository branch indicated by `configurations` variable
#    with:
#      configurations: staging
